project:
  type: website

website:
  title: "CV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.pdf
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



